import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import HeaderBar from "@/components/HeaderBar";
import Footer from "@/components/Footer";

const textFont = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
})

export const metadata: Metadata = {
  title: "XM | Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={textFont.className}>
        <main className="relative flex flex-col min-h-screen">
          <HeaderBar />
          <div className="flex-grow flex flex-col justify-center items-center flex-1 overflow-hidden">
            {children}
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
